# Generated by Django 5.2.4 on 2025-07-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='location',
        ),
        migrations.AddField(
            model_name='organicfood',
            name='description',
            field=models.TextField(default='No description yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='vendor@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='vendor@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organicfood',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
