# Generated by Django 5.2.4 on 2025-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0002_rename_shop_name_vendor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='No description yet'),
        ),
    ]
