# Generated by Django 5.2.4 on 2025-07-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0003_vendor_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_type', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
