# Generated by Django 5.2.4 on 2025-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0004_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
