# Generated by Django 5.2.4 on 2025-08-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0005_delete_food_alter_vendor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
    ]
