# Generated by Django 5.2.4 on 2025-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(default='Default Shop', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_place',
            field=models.CharField(default='Default Place', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
