# Generated by Django 5.2.4 on 2025-08-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0009_alter_vendor_password_alter_vendor_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organicfood',
            old_name='food_name',
            new_name='name',
        ),
    ]
