# Generated by Django 5.2.4 on 2025-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0010_rename_food_name_organicfood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
