# Generated by Django 5.2.4 on 2025-08-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0011_vendor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicfood',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organicfood',
            name='price',
        ),
    ]
