# Generated by Django 5.2.4 on 2025-08-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0012_remove_organicfood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicfood',
            name='fish_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organicfood',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
