# Generated by Django 5.2.4 on 2025-08-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0013_alter_organicfood_fish_type_alter_organicfood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
